In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
print(tf.__version__)

2.0.4


In [4]:
tf.test.is_gpu_available()

True

# 2.2 数据操作

在深度学习中，我们通常会频繁地对数据进行操作。

作为动手学深度学习的基础，本节将介绍如何对内存中的数据进行操作。

在 TensorFlow 中，tensor 是一个类，也是存储和变换数据的主要工具。

如果你之前用过 NumPy，你会发现 tensor 和 NumPy 的多维数组非常类似。然而，tensor 提供 GPU 计算和自动求梯度等更多功能，这些使 tensor 更加适合深度学习。

# 2.2.1 创建 tensor

我们先介绍 `tensor` 的最基本功能，我们用 `arange` 函数创建一个行向量。

In [5]:
x = tf.constant(range(12))
x

<tf.Tensor: id=0, shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

这时返回了一个 `tensor` 实例，其中包含了从 0 开始的 12 个连续整数。

我们可以通过 shape 属性来获取 tensor 实例的形状。

In [6]:
print(x.shape)

(12,)


我们也能够通过 len 得到 tensor 实例中元素（element）的总数。

In [7]:
len(x)

12

下面使用reshape函数把行向量x的形状改为(3, 4)，也就是一个3行4列的矩阵，并记作X。除了形状改变之外，X中的元素保持不变。



In [8]:
x = tf.reshape(x,(3,4))

In [9]:
x

<tf.Tensor: id=2, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

注意X属性中的形状发生了变化。上面x.reshape((3, 4))也可写成x.reshape((-1, 4))或x.reshape((3, -1))。由于x的元素个数是已知的，这里的-1是能够通过元素个数和其他维度的大小推断出来的。

接下来，我们创建一个各元素为0，形状为(2, 3, 4)的张量。实际上，之前创建的向量和矩阵都是特殊的张量。

In [10]:
X = tf.reshape(x,(-1,4))
X

<tf.Tensor: id=4, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [11]:
tf.zeros((2,3,4))

<tf.Tensor: id=7, shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

类似地，我们可以创建各元素为1的张量。



In [12]:
tf.ones((2,3,4))

<tf.Tensor: id=10, shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [13]:
tf.ones((3,4))

<tf.Tensor: id=13, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

我们也可以通过Python的列表（list）指定需要创建的tensor中每个元素的值。

In [14]:
Y = tf.constant([[1,2,3,4],[6,7,8,9],[10,11,12,13]])
Y

<tf.Tensor: id=14, shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]], dtype=int32)>

有些情况下，我们需要随机生成tensor中每个元素的值。下面我们创建一个形状为(3, 4)的tensor。它的每个元素都随机采样于均值为0、标准差为1的正态分布。



In [15]:
tf.random.normal(shape=[3,4], mean=0, stddev=1)

<tf.Tensor: id=20, shape=(3, 4), dtype=float32, numpy=
array([[-0.5090829 ,  1.8400015 , -0.43012455,  0.57284474],
       [ 0.8540833 ,  1.5494365 , -1.639329  ,  0.23374745],
       [ 0.7366344 ,  1.2346536 , -0.48547032, -0.17919974]],
      dtype=float32)>

# 2.2.2 运算

tensor支持大量的运算符（operator）。例如，我们可以对之前创建的两个形状为(3, 4)的tensor做按元素加法。所得结果形状不变。

In [16]:
X + Y

<tf.Tensor: id=21, shape=(3, 4), dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [10, 12, 14, 16],
       [18, 20, 22, 24]], dtype=int32)>

按元素乘法：



In [17]:
X * Y

<tf.Tensor: id=22, shape=(3, 4), dtype=int32, numpy=
array([[  0,   2,   6,  12],
       [ 24,  35,  48,  63],
       [ 80,  99, 120, 143]], dtype=int32)>

按元素除法：


In [18]:
X / Y

<tf.Tensor: id=25, shape=(3, 4), dtype=float64, numpy=
array([[0.        , 0.5       , 0.66666667, 0.75      ],
       [0.66666667, 0.71428571, 0.75      , 0.77777778],
       [0.8       , 0.81818182, 0.83333333, 0.84615385]])>

#### 按元素做指数运算：




In [19]:
Y = tf.cast(Y,tf.float32)
Y

<tf.Tensor: id=26, shape=(3, 4), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.],
       [ 6.,  7.,  8.,  9.],
       [10., 11., 12., 13.]], dtype=float32)>

In [20]:
tf.exp(Y)

<tf.Tensor: id=27, shape=(3, 4), dtype=float32, numpy=
array([[2.7182817e+00, 7.3890562e+00, 2.0085537e+01, 5.4598148e+01],
       [4.0342880e+02, 1.0966332e+03, 2.9809580e+03, 8.1030840e+03],
       [2.2026467e+04, 5.9874141e+04, 1.6275480e+05, 4.4241341e+05]],
      dtype=float32)>

除了按元素计算外，我们还可以使用 matmul 函数做矩阵乘法。下面将 X 与 Y 的转置做矩阵乘法。由于X是3行4列的矩阵，Y转置为4行3列的矩阵，因此两个矩阵相乘得到3行3列的矩阵。

In [21]:
X = tf.cast(X, tf.float32)

In [22]:
Y = tf.cast(Y, tf.float32)

In [23]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: id=31, shape=(3, 3), dtype=float32, numpy=
array([[ 20.,  50.,  74.],
       [ 60., 170., 258.],
       [100., 290., 442.]], dtype=float32)>

In [24]:
tf.matmul(tf.transpose(X), X)

<tf.Tensor: id=34, shape=(4, 4), dtype=float32, numpy=
array([[ 80.,  92., 104., 116.],
       [ 92., 107., 122., 137.],
       [104., 122., 140., 158.],
       [116., 137., 158., 179.]], dtype=float32)>

我们也可以将多个 tensor 连结（concatenate）。

下面分别在行上（维度0，即形状中的最左边元素）和列上（维度1，即形状中左起第二个元素）连结两个矩阵。

可以看到，输出的第一个 tensor 在维度0的长度（ 6 ）为两个输入矩阵在维度0的长度之和（ 3+3 ），而输出的第二个 tensor 在维度1的长度（ 8 ）为两个输入矩阵在维度1的长度之和（ 4+4 ）。

In [25]:
tf.concat([X,Y], axis=0)

<tf.Tensor: id=36, shape=(6, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 1.,  2.,  3.,  4.],
       [ 6.,  7.,  8.,  9.],
       [10., 11., 12., 13.]], dtype=float32)>

In [26]:
tf.concat([X,Y],axis=1)

<tf.Tensor: id=38, shape=(3, 8), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.,  6.,  7.,  8.,  9.],
       [ 8.,  9., 10., 11., 10., 11., 12., 13.]], dtype=float32)>

使用条件判断式可以得到元素为 0 或 1 的新的tensor。以 X == Y 为例，如果 X 和 Y 在相同位置的条件判断为真（值相等），那么新的tensor在相同位置的值为1；反之为0。

In [27]:
tf.equal(X,Y)

<tf.Tensor: id=39, shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

对 tensor 中的所有元素求和得到只有一个元素的 tensor 。

In [28]:
tf.reduce_sum(X)

<tf.Tensor: id=41, shape=(), dtype=float32, numpy=66.0>

In [29]:
X

<tf.Tensor: id=28, shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

## 求范数

矩阵范数是矩阵 $AA^T$ 最大特征值绝对值的开方

In [30]:
tf.norm(X)

<tf.Tensor: id=46, shape=(), dtype=float32, numpy=22.494444>

In [31]:
tf.linalg.eigh(tf.matmul(X, tf.transpose(X)))

(<tf.Tensor: id=50, shape=(3,), dtype=float32, numpy=array([1.31216475e-05, 3.82337117e+00, 5.02176636e+02], dtype=float32)>,
 <tf.Tensor: id=51, shape=(3, 3), dtype=float32, numpy=
 array([[-0.40825227,  0.90090555,  0.1473065 ],
        [ 0.81649536,  0.2882014 ,  0.50027525],
        [-0.4082468 , -0.32451352,  0.85324407]], dtype=float32)>)

In [32]:
np.sqrt(5.02176636e+02)

22.409297980972095

# 广播机制

前面我们看到如何对两个形状相同的 tensor 做按元素运算。

当对两个形状不同的 tensor 按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个 tensor 形状相同后再按元素运算。

定义两个 tensor：

In [33]:
A = tf.reshape(tf.constant(range(3)),(3,1))
B = tf.reshape(tf.constant(range(2)),(1,2))

In [34]:
A,B

(<tf.Tensor: id=54, shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: id=57, shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

由于 A 和 B 分别是 3 行 1 列和 1 行 2 列的矩阵，如果要计算 A + B，那么 A 中第一列的3个元素被广播（复制）到了第二列，而 B 中第一行的2个元素被广播（复制）到了第二行和第三行。如此，就可以对2个3行2列的矩阵按元素相加。

In [35]:
A+B

<tf.Tensor: id=58, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

# 2.2.4 索引

在 tensor 中，索引（index）代表了元素的位置。tensor 的索引从 0 开始逐一递增。例如，一个 3 行 2 列的矩阵的行索引分别为 0、1 和 2 ，列索引分别为 0 和 1 。

在下面的例子中，我们指定了 tensor 的行索引截取范围 [1:3] 。依据左闭右开指定范围的惯例，它截取了矩阵 X 中行索引为 1 和 2 的两行。

In [36]:
X[1:3]

<tf.Tensor: id=62, shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

我们可以指定 tensor 中需要访问的单个元素的位置，如矩阵中行和列的索引，并为该元素重新赋值。

In [37]:
X = tf.Variable(X)

In [38]:
X[1,2].assign(9)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

当然，我们也可以截取一部分元素，并为它们重新赋值。在下面的例子中，我们为行索引为 1 的每一列元素重新赋值。

In [39]:
X[1,:].assign(tf.ones(X[1,:].shape,dtype=tf.float32)*12)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

# 2.2.5 运算的内存开销

在前面的例子里我们对每个操作新开内存来存储运算结果。举个例子，即使像 Y = X + Y 这样的运算，我们也会新开内存，然后将 Y 指向新内存。为了演示这一点，我们可以使用 Python 自带的 id 函数：如果两个实例的 ID 一致，那么它们所对应的内存地址相同；反之则不同。

In [40]:
before = id(Y)

In [41]:
before

139975477875096

In [42]:
Y = Y + X

In [43]:
id(Y) == before

False

如果想指定结果到特定内存，我们可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们先通过 zeros_like 创建和 Y 形状相同且元素为 0 的tensor，记为 Z 。

接下来，我们把 X + Y 的结果通过 [:] 写进 Z 对应的内存中。

In [44]:
Z = tf.Variable(tf.zeros_like(Y))

In [45]:
Z

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [46]:
before = id(Z)

In [47]:
Z[:].assign(X + Y)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 1.,  4.,  7., 10.],
       [30., 31., 32., 33.],
       [26., 29., 32., 35.]], dtype=float32)>

In [48]:
id(Z) == before

True

实际上，上例中我们还是为 `X + Y` 开了临时内存来存储计算结果，再复制到 `Z` 对应的内存。

如果想避免这个临时内存开销，我们可以使用assign_{运算符全名}函数。

In [49]:
Z = tf.add(X, Y)
id(Z) == before

False

In [50]:
before = id(X)

In [51]:
X.assign_add(Y)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 1.,  4.,  7., 10.],
       [30., 31., 32., 33.],
       [26., 29., 32., 35.]], dtype=float32)>

In [52]:
id(X) == before

True

如果 `X` 的值在之后的程序中不会复用，我们也可以用 `X[:] = X + Y` 或者 `X += Y` 来减少运算的内存开销。

# 2.2.6 tensor 和 NumPy 相互变换

我们可以通过 array 函数和 asnumpy 函数令数据在 NDArray 和 NumPy 格式之间相互变换。下面将 NumPy 实例变换成 tensor 实例。

In [53]:
P = np.ones((2,3))

In [54]:
D = tf.constant(P)

In [55]:
D

<tf.Tensor: id=115, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

再将 NDArray 实例变换成 NumPy 实例。

In [56]:
np.array(D)

array([[1., 1., 1.],
       [1., 1., 1.]])